### ISSUE TITLE
Clear Nonces does not clear expired nonces

### ISSUE THREAD

**Issue by krispy1298** [calevans/wp-simple-nonce#7]
https://github.com/wahabmirjan/wp-simple-nonce/blob/master/WPSimpleNonce.php#L108

Shouldn't the `option_value>time()+86400` be `option_value<time()+86400` or `option_value<time()`?

**Comment by phl43** [comment]
Yes, if I understand correctly this method is called once a day to clear expired nonces, so presumably the condition should be ```$singleNonce->option_value < time()```. Unless we are mistaken, this seems like a pretty serious bug. @calevans, if you are still around, could you please tell us what you think?

**Comment by wahabmirjan** [comment]
Resolved. Will be released in v1.4

**Comment by wahabmirjan** [comment]
Reopening. Realised that expiration time is incorrectly calculated.

**Comment by wahabmirjan** [comment]
Resolved
